version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: python --version
      - run: python main.py
test:
  docker:
    -image: cimg/python:3.8
  steps:
      - checkout
      - run: python --version
      - run: python main.py
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test